sudo: no
language: node_js
branches:
  only:
  - master
install:
- npm install
script:
- npm run lint
- npm run test
notifications:
  email: false
deploy:
  provider: npm
  email: lonnen@mozilla.com
  api_key:
    secure: a+RxKYrMVIA7B/SiphMVLBVlaeuufTwas6bdUlYCJWlzMugtKBDqnYu4NN9qTdQIOmy5Z0zgnOxvf8VQEfLQ3B3rJTw6/JSl3FlSfmoiWmTxRJx4MCYXpJykAgvdZeKIysG91watX/BQRYS3LR8KkxER/coqiLoOMtZwAfrQO2Y=
  on:
    tags: true
    repo: mozilla/corsica
